name: Update latest blog posts

on:
  schedule:
    - cron: "7 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    if: ${{ vars.BLOG_RSS_URL != '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v4.6.0
      - name: Insert the five most recent posts
        uses: gautamkrishnar/blog-post-workflow@2786e54a01b71aec80a5118c2bd6b5044e842597 # v1.9.3
        with:
          feed_list: ${{ vars.BLOG_RSS_URL }}
          max_post_count: "5"
          comment_tag_name: BLOG-POST-LIST
          template: "$newline- [$title]($url)$newline"
          commit_message: "chore: refresh blog posts"
