name: Generate contribution snake

on:
  schedule:
    - cron: "17 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v4.6.0
      - name: Generate light and dark snakes
        uses: Platane/snk@a041d6c27ba561a39f5be9c26a784812765e434b # v3
        with:
          github_user_name: vighriday
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Publish generated SVGs to output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash scripts/publish_output_branch.sh ./dist "chore: refresh contribution snake"
