name: Update weekly WakaTime coding stats

on:
  schedule:
    - cron: "37 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    if: ${{ vars.ENABLE_WAKATIME == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v4.6.0
      - name: Insert weekly coding-time breakdown
        uses: athul/waka-readme@370590ad8da8f54282ed92aa42b7c25ecbd5a9a6 # master at 2026-08-01
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: "chore: refresh WakaTime stats"
          SHOW_TITLE: true
          BLOCKS: ░▒▓█
          TIME_RANGE: last_7_days
